### ISSUE TITLE
Custom 'x-api-request-version' header

### ISSUE THREAD

**Issue by jbrooksuk** [tomschlick/request-migrations#12]
https://github.com/tomschlick/request-migrations/blob/fb5471b63a7a2619ba64a6576a4162bfb5d92120/src/Migrator.php#L36

I think this should be custom.

**Comment by tomschlick** [comment]
yeah thats on my list. both the ability to set that from a custom variable with a header override and to rename the header entirely.

**Comment by jbrooksuk** [comment]
👍

**Comment by tomschlick** [comment]
You can now customize all header names.
