### ISSUE TITLE
Should default to current version

### ISSUE THREAD

**Issue by sixlive** [tomschlick/request-migrations#41]
Given

`request-migrations.php`
```php
'current_version' => '2017-09-18',
'versions' => [
    '2017-09-18' => [],
    '2017-09-17' => [
        \App\Http\Migrations\FooMigration::class
    ]
],
```

It shouldn't run any migrations and default to the current version: `2017-09-18`. Currently, it runs the migration for `2017-09-17`.

Labeling as a 'Bug' because I think this was the intended functionality but I can't recall.

**Comment by tomschlick** [comment]
Yeah thats a bug. We should be checking that there are actual changes to run between the versions. Thats where the `request_version` and `response_version` could differ.
